export const data=[
    {   id:1,
        title:"The ministrel boy ",
        auteur:"Archibald Joseph Cronin",
        imgUrl:"https://tse4.mm.bing.net/th?id=OIP.fvKPVAknCXJ5cOB2O8RJHgAAAA&pid=Api&P=0&w=94&h=158",
        categorie:"New English Librairy-1977",
        prix:"5.17$",
    },
    {
        id:2,
        title:"The solid mandala ",
        auteur:"Patrick White",
        imgUrl:"https://tse2.mm.bing.net/th?id=OIP.Y5i5ZmJPxDQ64JTIIjYPIgDhEs&pid=Api&P=0&w=118&h=157",
        categorie:"Fiction-1981",
        prix:"8.06$",
    },
    {   id:3,
        title:"Scarlet Ribbons ",
        auteur:"Emma Blair",
        imgUrl:"https://tse1.mm.bing.net/th?id=OIP.Z2PvSjXzCgK-uRgoIS8cDAAAAA&pid=Api&P=0&w=108&h=168",
        categorie:"Bantam Books-1992",
        prix:"5.21$",

    },
    {   id:4,
        title:"Goddess ",
        auteur:"Margaret Pemberton",
        imgUrl:"https://tse4.mm.bing.net/th?id=OIP.BWdbr9pYqgmTEyrha697BQHaFj&pid=Api&P=0&w=212&h=159",
        categorie:"Bantam Books-1985",
        prix:"12.00$",
    },
    {   id:5,
        title:"The Public Image ",
        auteur:"Muriel Spark",
        imgUrl:"https://tse4.mm.bing.net/th?id=OIP.rb7WoPc7U7JSeOr71L01AAAAAA&pid=Api&P=0&w=98&h=157",
        categorie:"Fiction-1989",
        prix:"3.12$",
    },
    {   id:6,
        title:"Cancer World ",
        auteur:"Alexandre Soljénitsyne",
        imgUrl:"https://tse2.explicit.bing.net/th?id=OIP.ZlI2sOXZh2Szkg0_Y0_JkAAAAA&pid=Api&P=0&w=175&h=175",
        categorie:"Fiction-1974",
        prix:"4.76$",
    },

]